version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.14.1-jessie
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Generate static site
          command: npm run generate
      - run:
          name: Deploy to Firebase
          command: npm run deploy:ci

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
